language: c, python3

addons:
  apt:
    packages:
      - re2c

before_install:
  - export FOSS_DIR=~/foss

install:
  - DIR=$(FOSS_DIR)/ninja
  - tools/install-ninja $(DIR)
  - export PATH=$(DIR):$PATH

cache:
  directories:
    - $(FOSS_DIR)

script:
  - ninja --version
  - make Posix
  - make run-posix
