language: c, python3

addons:
  apt:
    packages:
      - re2c

install:
  - git clone https://github.com/martine/ninja.git
  - cd ninja
  - ./configure.py --bootstrap
  - export PATH=$(pwd):$PATH
  - cd ..

cache:
  directories:
    - ninja

script:
  - ninja --version
  - make Posix
  - make run-posix
