language: c, python3

env:
  global:
    - FOSS_DIR=~/foss
  matrix:
    - Platform=Posix

addons:
  apt:
    packages:
      - re2c
      - qemu-system-arm

install:
  - DIR="${FOSS_DIR}/ninja"
  - tools/install-ninja ${DIR}
  - export PATH=${DIR}:$PATH

cache:
  directories:
    - ${FOSS_DIR}

script:
  - ninja --version
  - make ${Platform}
  - make run-${Platform}
