language: c, python3
install:
  - git clone https://github.com/martine/ninja.git
  - cd ninja
  - ./configure.py --bootstrap
  - export PATH=$(pwd)/ninja:$PATH

script:
  - export $PATH
  - which ninja
  - ninja --version
  - make Posix
  - make run-posix
