language: c, python3

addons:
  apt:
    packages:
      - re2c

install:
  - export FOSS_DIR=~/foss
  - DIR="${FOSS_DIR}/ninja"
  - tools/install-ninja ${DIR}
  - export PATH=${DIR}:$PATH

cache:
  directories:
    - ~/foss

script:
  - ninja --version
  - make Posix
  - make run-posix
