language: python
sudo: false

python:
  - "3.5"

env:
  global:
    - INSTALL_DIR=$HOME/opt
    - CACHE_DIR=$HOME/cached
    - TMP_DIR=$HOME/tmp
  matrix:
    - Platform=Posix

cache:
  directories:
    - ${INSTALL_DIR}
    - ${CACHED_DIR}

addons:
  apt:
    packages:
      - re2c # Needed by ninja
        #- qemu-system-arm  # Doesn't install!!

before_install:
  - export PATH=${INSTALL_DIR}/bin:$PATH
  - python --version
  - python2 --version
  - python3 --version
  - virtualenv --version

install:
  - tools/install-ninja.py --tmp ${TMP_DIR} --prefix ${INSTALL_DIR}
  - DIR="${TMP_DIR}/qemu"
  - tools/install-qemu ${DIR}
  - export PATH=${DIR}/build/arm-softmmu:$PATH

before_script:
  - ninja --version
  - qemu-system-arm --version

script:
  - make ${Platform}
  - make run-${Platform}
