language: python
sudo: false

python:
  - "3.5"

env:
  global:
    - FOSS_DIR=~/foss
  matrix:
    - Platform=Posix

cache:
  directories:
    - ${FOSS_DIR}

addons:
  apt:
    packages:
      - re2c # Needed by ninja
        #- qemu-system-arm  # Doesn't install!!

before_install:
  - python --version
  - python2 --version
  - python3 --version
  - virtualenv --version

install:
  - DIR="${FOSS_DIR}/ninja"
  - tools/install-ninja ${DIR}
  - export PATH=${DIR}:$PATH
  - DIR="${FOSS_DIR}/qemu"
  - tools/install-qemu ${DIR}
  - export PATH=${DIR}/build/arm-softmmu:$PATH

before_script:
  - ninja --version
  - qemu-system-arm --version

script:
  - make ${Platform}
  - make run-${Platform}
