language: c, python3

addons:
  apt:
    packages:
      - re2c

install:
  - DIR=`pwd`
  - if [ ! -d "~/foss/ninja" ]: then
  -   mkdir ~/foss/ninja
  -   git clone https://github.com/martine/ninja.git ~/foss/ninja
  -   cd ~/foss/ninja
  -   ./configure.py --bootstrap
    fi
  - export PATH=$(pwd):$PATH
  - cd $DIR

cache:
  directories:
    - ~/foss

script:
  - ninja --version
  - make Posix
  - make run-posix
