language: c, python3

env:
  global:
    - FOSS_DIR=~/foss
  matrix:
    - Platform=Posix

addons:
  apt:
    packages:
      - re2c
      - virtualenv
      - virtualenv2

install:
  - DIR="${FOSS_DIR}/ninja"
  - tools/install-ninja ${DIR}
  - export PATH=${DIR}:$PATH
  - DIR="${FOSS_DIR}/qemu"
  - tools/install-qemu ${DIR}
  - export PATH=${DIR}/build/arm-softmmu:$PATH

cache:
  directories:
    - ${FOSS_DIR}

script:
  - ninja --version
  - qemu-system-arm --version
  - make ${Platform}
  - make run-${Platform}
