language: python
sudo: false

python:
  - "3.5"

env:
  global:
    - FOSS_DIR=~/foss
  matrix:
    - Platform=Posix

addons:
  apt:
    packages:
      - re2c
      - python3.5-venv
        #- qemu
      - qemu-system-arm
        #- dtc

before_install:
  #- sudo pip install virtualenv
  - python --version
  - python2 --version
  - python3 --version
  - virtualenv --version
  - qemu-system-arm --version

install:
  - DIR="${FOSS_DIR}/ninja"
  - tools/install-ninja ${DIR}
  - export PATH=${DIR}:$PATH
  #- DIR="${FOSS_DIR}/qemu"
  #- tools/install-qemu ${DIR}
  #- export PATH=${DIR}/build/arm-softmmu:$PATH

cache:
  directories:
    - ${FOSS_DIR}

script:
  - ninja --version
    #- qemu-system-arm --version
  - make ${Platform}
  - make run-${Platform}
