# Copyright 2015 wink saville
#
# licensed under the apache license, version 2.0 (the "license");
# you may not use this file except in compliance with the license.
# you may obtain a copy of the license at
#
#     http://www.apache.org/licenses/license-2.0
#
# unless required by applicable law or agreed to in writing, software
# distributed under the license is distributed on an "as is" basis,
# without warranties or conditions of any kind, either express or implied.
# see the license for the specific language governing permissions and
# limitations under the license.

language: python
sudo: false

python:
  - "3.5"

env:
  global:
    - INSTALL_DIR=$HOME/opt
    - BIN_DIR=${INSTALL_DIR}/bin
    - CACHE_DIR=$HOME/cached
    - SRC_DIR=$HOME/tmp
  matrix:
    - Platform=Posix

cache:
  directories:
    #- ${INSTALL_DIR}
    #- ${CACHED_DIR}

addons:
  apt:
    packages:
      - textinfo
      - re2c # Needed by ninja
        #- qemu-system-arm  # Doesn't install!!

before_install:
  - mkdir -p ${BIN_DIR}
  - mkdir -p ${CROSS_BIN_DIR}
  - export PATH=${BIN_DIR}:$PATH
  - export PATH=${CROSS_BIN_DIR}:$PATH

install:
  - wget 'https://docs.google.com/uc?export=download&id=0B-KTY7zi7eZHWFJxNzFBNkkxS0U' -O ${BIN_DIR}/ninja.tgz
  - tar -xzf ${BIN_DIR}/ninja.tgz -O > ${BIN_DIR}/ninja
  #- tools/ninja-install.py --src ${SRC_DIR}/ninja --prefix ${INSTALL_DIR}
  #- tools/qemu-install.py --src ${SRC_DIR}/qemu --prefix ${INSTALL_DIR}
  #- tools/binutils-install.py --src ${SRC_DIR}/binutils --prefix ${INSTALL_DIR}/cross

before_script:
  - python --version
  - python2 --version
  - python3 --version
  - virtualenv --version
  - ninja --version
    #- qemu-system-arm --version

script:
  - make ${Platform}
  - make run-${Platform}
