#!/usr/bin/env bash
#set -x
set -e

VER=2.4.0.1

# Test if we've got the desired version
if [[ `$1/build/arm-softmmu/qemu-system-arm -version` == *"${VER}"* ]]; then
  echo "qemu-system-arm ${VER} is available";
else
  mkdir -p $1
  git clone git://git.qemu.org/qemu.git $1
  cd $1
  git checkout v${VER}
  git submodule update --init dtc
  mkdir build
  cd build
  virtualenv --python=python2.7 venv
  . venv/bin/activate
  ../configure --target-list=arm-softmmu,arm-linux-user
  make
fi
